use async_trait::async_trait;
use qimen_error::Result;
use qimen_message::{Message, Segment};
use qimen_plugin_api::Module;
use qimen_protocol_core::NormalizedEvent;


#[derive(Default)]
pub struct CommandModule;

#[async_trait]
impl Module for CommandModule {
    fn id(&self) -> &'static str {
        "command"
    }

    async fn on_load(&self) -> Result<()> {
        Ok(())
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CommandTrigger {
    Private,
    Prefix,
    Mention,
    Reply,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum BuiltinCommand {
    Ping,
    Echo(String),
    Status,
    Help,
    Plugins,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MatchedCommand {
    pub trigger: CommandTrigger,
    pub command: BuiltinCommand,
    pub source_text: String,
}

pub fn match_builtin_command(event: &NormalizedEvent) -> Option<MatchedCommand> {
    let message = event.message.as_ref()?;

    if is_private_chat(event) {
        let text = message.plain_text();
        return parse_builtin(text.trim()).map(|command| MatchedCommand {
            trigger: CommandTrigger::Private,
            command,
            source_text: text,
        });
    }

    if let Some(text) = strip_prefix_command_text(message) {
        return parse_builtin(&text).map(|command| MatchedCommand {
            trigger: CommandTrigger::Prefix,
            command,
            source_text: message.plain_text(),
        });
    }

    if let Some(text) = strip_mention_command_text(event, message) {
        return parse_builtin(&text).map(|command| MatchedCommand {
            trigger: CommandTrigger::Mention,
            command,
            source_text: message.plain_text(),
        });
    }

    if let Some(text) = strip_reply_command_text(message) {
        return parse_builtin(&text).map(|command| MatchedCommand {
            trigger: CommandTrigger::Reply,
            command,
            source_text: message.plain_text(),
        });
    }

    None
}

pub fn build_builtin_reply(bot_label: &str, command: &BuiltinCommand) -> Message {
    match command {
        BuiltinCommand::Ping => Message::text("pong"),
        BuiltinCommand::Echo(text) => Message::text(text.clone()),
        BuiltinCommand::Status => Message::text(format!(
            "bot={} protocol=onebot11 transport=ws-forward status=ok",
            bot_label
        )),
        BuiltinCommand::Help => Message::text("help is generated by command dispatcher"),
        BuiltinCommand::Plugins => Message::text("plugins status is generated by command dispatcher"),
    }
}

fn parse_builtin(input: &str) -> Option<BuiltinCommand> {
    let normalized = input.trim();
    let normalized = normalized.strip_prefix('/').unwrap_or(normalized).trim();

    if normalized.eq_ignore_ascii_case("ping") {
        return Some(BuiltinCommand::Ping);
    }

    if normalized.eq_ignore_ascii_case("status") {
        return Some(BuiltinCommand::Status);
    }

    if normalized.eq_ignore_ascii_case("help") {
        return Some(BuiltinCommand::Help);
    }

    if normalized.eq_ignore_ascii_case("plugins") {
        return Some(BuiltinCommand::Plugins);
    }

    if let Some(rest) = strip_command_head(normalized, "echo") {
        return Some(BuiltinCommand::Echo(rest.to_string()));
    }

    None
}

fn strip_command_head<'a>(input: &'a str, command: &str) -> Option<&'a str> {
    let rest = input.strip_prefix(command)?;
    let trimmed = rest.trim_start();
    if trimmed.is_empty() {
        return Some("");
    }
    Some(trimmed)
}

pub fn strip_command_name_and_args(input: &str) -> Option<(&str, Vec<String>)> {
    let trimmed = input.trim();
    if trimmed.is_empty() {
        return None;
    }

    let mut parts = trimmed.split_whitespace();
    let name = parts.next()?;
    let args = parts.map(|part| part.to_string()).collect();
    Some((name, args))
}

fn is_private_chat(event: &NormalizedEvent) -> bool {
    event.is_private()
}

fn strip_prefix_command_text(message: &Message) -> Option<String> {
    let text = message.plain_text();
    let trimmed = text.trim();
    if trimmed.starts_with('/') {
        Some(trimmed.to_string())
    } else {
        None
    }
}

fn strip_mention_command_text(event: &NormalizedEvent, message: &Message) -> Option<String> {
    let self_id = event.self_id_str()?;
    let remaining = strip_leading_self_mentions(&message.segments, &self_id)?;
    let text = remaining
        .iter()
        .filter_map(segment_text)
        .collect::<Vec<_>>()
        .join("");
    let trimmed = text.trim();
    if trimmed.is_empty() {
        return None;
    }

    if let Some(command) = trimmed.strip_prefix('/') {
        return Some(command.trim().to_string());
    }

    Some(trimmed.to_string())
}

fn strip_reply_command_text(message: &Message) -> Option<String> {
    let remaining = strip_leading_reply_segments(&message.segments)?;
    let text = remaining
        .iter()
        .filter_map(segment_text)
        .collect::<Vec<_>>()
        .join("");
    let trimmed = text.trim();
    if trimmed.is_empty() {
        None
    } else {
        Some(trimmed.to_string())
    }
}

fn strip_leading_self_mentions<'a>(segments: &'a [Segment], self_id: &str) -> Option<&'a [Segment]> {
    let mut index = 0;
    let mut seen_mention = false;

    while let Some(segment) = segments.get(index) {
        if is_self_at_segment(segment, self_id) {
            seen_mention = true;
            index += 1;
            continue;
        }

        if seen_mention && is_whitespace_text_segment(segment) {
            index += 1;
            continue;
        }

        break;
    }

    if seen_mention {
        Some(&segments[index..])
    } else {
        None
    }
}

fn strip_leading_reply_segments(segments: &[Segment]) -> Option<&[Segment]> {
    let mut index = 0;
    let mut seen_reply = false;

    while let Some(segment) = segments.get(index) {
        if segment.kind == "reply" {
            seen_reply = true;
            index += 1;
            continue;
        }

        if seen_reply && is_whitespace_text_segment(segment) {
            index += 1;
            continue;
        }

        break;
    }

    if seen_reply {
        Some(&segments[index..])
    } else {
        None
    }
}

fn is_self_at_segment(segment: &Segment, self_id: &str) -> bool {
    segment
        .at_target()
        .map(|target| target == self_id || (target.eq_ignore_ascii_case("all") && self_id == "all"))
        .unwrap_or(false)
}

fn is_whitespace_text_segment(segment: &Segment) -> bool {
    segment
        .get_text()
        .is_some_and(|text| text.trim().is_empty())
}

fn segment_text(segment: &Segment) -> Option<&str> {
    segment.get_text()
}
