[package]
name = "qimen-transport-qqbot"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
bytes.workspace = true
futures-util.workspace = true
md5.workspace = true
qimen-error = { path = "../qimen-error" }
qimen-transport-ws = { path = "../qimen-transport-ws" }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sha1.workspace = true
tokio.workspace = true
tracing.workspace = true
reqwest = { version = "0.12", default-features = false, features = ["json", "multipart", "rustls-tls-webpki-roots"] }
